<?php
declare(strict_types=1);

$services = [
    'website-development' => [
        'name' => 'Website Development',
        'title' => 'Website Development Company in Pune for Fast, SEO-Ready Websites',
        'meta' => 'Mega Techzy builds premium business websites in Pune, PCMC and Solapur with SEO, speed, security and lead generation built in from day one.',
        'intro' => 'We design and develop conversion-focused websites that feel premium, load fast and make it easy for customers to trust your business.',
        'proof' => 'Every build includes responsive layouts, technical SEO, analytics setup, secure forms and a content structure that can scale into location and service pages.',
        'icon' => 'code',
        'outcomes' => ['Premium brand presence', 'Better Google crawlability', 'More qualified enquiries', 'Faster mobile experience'],
        'deliverables' => ['UX sitemap and wireframe', 'Responsive PHP/HTML/CSS build', 'On-page SEO foundations', 'Lead form and analytics integration'],
        'related' => ['seo', 'lead-generation', 'analytics'],
        'faqs' => [
            ['q' => 'How long does a business website take?', 'a' => 'Most focused business websites take 2 to 5 weeks depending on page count, content readiness and integrations.'],
            ['q' => 'Do you build SEO into the website?', 'a' => 'Yes. Site structure, metadata, schema, speed, internal links and conversion paths are planned before development begins.'],
        ],
    ],
    'seo' => [
        'name' => 'Search Engine Optimization',
        'title' => 'SEO Company in Pune for Local Rankings and Organic Leads',
        'meta' => 'Improve local rankings, organic traffic and lead quality with Mega Techzy SEO services for Pune, PCMC, Solapur and Maharashtra businesses.',
        'intro' => 'Our SEO programs help search engines understand your business, location relevance, services and proof of expertise.',
        'proof' => 'We combine technical fixes, content planning, local landing pages, Google Business Profile improvements and reporting that connects rankings to leads.',
        'icon' => 'search',
        'outcomes' => ['Higher local visibility', 'More non-paid enquiries', 'Clear content roadmap', 'Improved technical health'],
        'deliverables' => ['SEO audit', 'Keyword and competitor research', 'On-page optimization', 'Local SEO and reporting'],
        'related' => ['content-marketing', 'website-development', 'analytics'],
        'faqs' => [
            ['q' => 'Can SEO help a local Pune business?', 'a' => 'Yes. Local SEO can improve visibility for searches such as digital marketing company in Pune and service-specific local terms.'],
            ['q' => 'When can SEO results start?', 'a' => 'Meaningful movement usually begins within 8 to 12 weeks, with compounding gains as content and authority improve.'],
        ],
    ],
    'google-ads' => [
        'name' => 'Google Ads',
        'title' => 'Google Ads Agency in Pune for Lead Generation Campaigns',
        'meta' => 'Launch conversion-focused Google Ads campaigns with landing pages, tracking and optimization from Mega Techzy.',
        'intro' => 'We run search and performance campaigns that focus on qualified enquiries, not empty clicks.',
        'proof' => 'Campaigns are structured around buyer intent, negative keywords, landing page quality, conversion tracking and weekly optimization.',
        'icon' => 'megaphone',
        'outcomes' => ['Faster demand capture', 'Cleaner search intent', 'Measurable CPL', 'Better landing page quality'],
        'deliverables' => ['Account audit', 'Campaign setup', 'Conversion tracking', 'Search term and bid optimization'],
        'related' => ['lead-generation', 'analytics', 'website-development'],
        'faqs' => [
            ['q' => 'Do you manage small Google Ads budgets?', 'a' => 'Yes. We structure campaigns around the budget, service area and lead target instead of forcing a generic setup.'],
            ['q' => 'Will I know which leads came from ads?', 'a' => 'Yes. We configure conversion tracking through GA4, GTM or platform-native tools wherever possible.'],
        ],
    ],
    'meta-ads' => [
        'name' => 'Meta Ads',
        'title' => 'Meta Ads Agency for Facebook and Instagram Campaigns',
        'meta' => 'Generate awareness, retarget visitors and capture leads with Facebook and Instagram ads managed by Mega Techzy.',
        'intro' => 'Meta campaigns work best when creative, audience, offer and follow-up are aligned. We build that system for growing brands.',
        'proof' => 'We test hooks, creatives, retargeting windows and lead forms while keeping tracking and campaign hygiene tight.',
        'icon' => 'megaphone',
        'outcomes' => ['Stronger brand reach', 'Retargeted website visitors', 'Lead form campaigns', 'Creative testing rhythm'],
        'deliverables' => ['Campaign strategy', 'Creative direction', 'Audience setup', 'Weekly performance optimization'],
        'related' => ['social-media', 'video-marketing', 'lead-generation'],
        'faqs' => [
            ['q' => 'Are Meta Ads good for B2B?', 'a' => 'They can be effective for retargeting, awareness and offer-led lead generation when the funnel is planned properly.'],
            ['q' => 'Do you create ad creatives?', 'a' => 'Yes. We can plan graphics, reels and copy for campaign testing.'],
        ],
    ],
    'linkedin-ads' => [
        'name' => 'LinkedIn Ads',
        'title' => 'LinkedIn Ads for B2B Lead Generation in India',
        'meta' => 'Reach decision makers with LinkedIn Ads strategy, targeting, creative and reporting by Mega Techzy.',
        'intro' => 'LinkedIn Ads help B2B companies reach specific roles, industries and company sizes with a focused message.',
        'proof' => 'We design campaigns for high-value audiences, clean conversion paths and sales follow-up readiness.',
        'icon' => 'linkedin',
        'outcomes' => ['Decision-maker reach', 'B2B lead quality', 'Account-based targeting', 'Stronger remarketing'],
        'deliverables' => ['Audience strategy', 'Campaign setup', 'Creative testing', 'Lead quality review'],
        'related' => ['lead-generation', 'content-marketing', 'analytics'],
        'faqs' => [
            ['q' => 'Is LinkedIn Ads expensive?', 'a' => 'Clicks can cost more than other platforms, so we use LinkedIn when targeting precision and lead value justify it.'],
            ['q' => 'Can LinkedIn Ads support sales teams?', 'a' => 'Yes. Campaigns can be built around lead magnets, demo requests and account-based follow-up.'],
        ],
    ],
    'email-marketing' => [
        'name' => 'Email Marketing and Zoho Automation',
        'title' => 'Email Marketing and Zoho Automation for Better Follow-Up',
        'meta' => 'Automate lead nurturing, follow-ups and reporting with email marketing and Zoho workflows from Mega Techzy.',
        'intro' => 'Most leads need consistent follow-up. We build email and Zoho automations that keep prospects moving.',
        'proof' => 'Workflows can include segmentation, CRM fields, lead source tracking, sales reminders and lifecycle reporting.',
        'icon' => 'automation',
        'outcomes' => ['Faster response time', 'Better lead nurturing', 'Cleaner CRM data', 'Repeatable follow-up'],
        'deliverables' => ['Journey mapping', 'Email copy', 'Zoho workflow setup', 'Testing and reporting'],
        'related' => ['lead-generation', 'whatsapp-marketing', 'analytics'],
        'faqs' => [
            ['q' => 'Can you work with Zoho CRM?', 'a' => 'Yes. We can plan and configure practical Zoho automations for lead capture and follow-up.'],
            ['q' => 'Do you write the email content?', 'a' => 'Yes. We write concise, conversion-focused email sequences based on the customer journey.'],
        ],
    ],
    'whatsapp-marketing' => [
        'name' => 'WhatsApp Marketing',
        'title' => 'WhatsApp Marketing for Lead Follow-Up and Customer Engagement',
        'meta' => 'Use WhatsApp campaigns and follow-up flows to improve response rates and customer engagement with Mega Techzy.',
        'intro' => 'WhatsApp can turn slow follow-up into timely conversations when it is used with consent, context and helpful messaging.',
        'proof' => 'We plan opt-in flows, templates, segmentation and handoff points so WhatsApp supports sales instead of spamming customers.',
        'icon' => 'whatsapp',
        'outcomes' => ['Higher response rates', 'Quicker lead contact', 'Segmented campaigns', 'Better sales handoff'],
        'deliverables' => ['Messaging strategy', 'Template planning', 'Audience segmentation', 'Campaign reporting'],
        'related' => ['email-marketing', 'lead-generation', 'meta-ads'],
        'faqs' => [
            ['q' => 'Is WhatsApp marketing suitable for every business?', 'a' => 'It works best when customers expect quick updates, consultations, bookings or support.'],
            ['q' => 'Do you help avoid spammy messaging?', 'a' => 'Yes. We prioritize consent, useful context and sensible frequency.'],
        ],
    ],
    'analytics' => [
        'name' => 'Analytics, GA4 and GTM',
        'title' => 'GA4, GTM and Looker Studio Analytics Setup',
        'meta' => 'Measure leads, campaigns and website performance with GA4, GTM and Looker Studio dashboards by Mega Techzy.',
        'intro' => 'Good marketing decisions need clean measurement. We set up analytics that make lead sources and performance easier to trust.',
        'proof' => 'We configure events, conversions, tags, dashboard views and checks so reporting supports real business decisions.',
        'icon' => 'chart',
        'outcomes' => ['Reliable conversion data', 'Campaign attribution', 'Readable dashboards', 'Cleaner optimization'],
        'deliverables' => ['GA4 setup', 'GTM configuration', 'Conversion events', 'Looker Studio dashboard'],
        'related' => ['google-ads', 'seo', 'lead-generation'],
        'faqs' => [
            ['q' => 'Can you fix broken tracking?', 'a' => 'Yes. We audit tags, events, forms and thank-you flows to find gaps.'],
            ['q' => 'Do dashboards update automatically?', 'a' => 'Looker Studio dashboards can refresh from connected data sources when configured correctly.'],
        ],
    ],
    'branding' => [
        'name' => 'Branding and Graphic Design',
        'title' => 'Branding Agency in Pune for Modern Business Identity',
        'meta' => 'Create a consistent brand identity, marketing creatives and design system with Mega Techzy branding services.',
        'intro' => 'Strong branding makes your business easier to remember, trust and choose across every customer touchpoint.',
        'proof' => 'We connect logo, color, typography, social creatives and website design into one consistent visual system.',
        'icon' => 'palette',
        'outcomes' => ['Professional identity', 'Consistent campaigns', 'Better recall', 'Stronger website trust'],
        'deliverables' => ['Brand direction', 'Logo refinement', 'Social creatives', 'Website visual system'],
        'related' => ['website-development', 'social-media', 'content-marketing'],
        'faqs' => [
            ['q' => 'Can you refresh an existing brand?', 'a' => 'Yes. We can modernize the visual language while preserving recognition.'],
            ['q' => 'Do you design social media creatives?', 'a' => 'Yes. Branding can include templates and campaign graphics for ongoing marketing.'],
        ],
    ],
    'social-media' => [
        'name' => 'Social Media Management',
        'title' => 'Social Media Management for Consistent Brand Growth',
        'meta' => 'Plan, create and manage social media content that supports brand trust, campaigns and lead generation.',
        'intro' => 'Social media works when it has a clear role: trust-building, education, demand creation or campaign support.',
        'proof' => 'We create calendars, content pillars, captions, creatives and reports that align with business goals.',
        'icon' => 'share',
        'outcomes' => ['Consistent posting', 'Better brand trust', 'Campaign support', 'Clear content direction'],
        'deliverables' => ['Content strategy', 'Monthly calendar', 'Creative production', 'Performance reporting'],
        'related' => ['meta-ads', 'branding', 'video-marketing'],
        'faqs' => [
            ['q' => 'Do you post for businesses monthly?', 'a' => 'Yes. We can manage monthly calendars, creatives, captions and publishing workflows.'],
            ['q' => 'Can social media generate leads?', 'a' => 'It can support lead generation when paired with offers, ads, retargeting and clear calls to action.'],
        ],
    ],
    'content-marketing' => [
        'name' => 'Content Marketing',
        'title' => 'Content Marketing for SEO, Trust and Demand Generation',
        'meta' => 'Build useful blogs, landing pages and content assets that improve SEO visibility and buyer trust.',
        'intro' => 'Content should answer buyer questions better than competitors while guiding readers toward the next step.',
        'proof' => 'We plan topic clusters, service pages, local content and sales enablement assets with SEO intent in mind.',
        'icon' => 'search',
        'outcomes' => ['More search coverage', 'Better buyer education', 'Reusable sales assets', 'Stronger authority'],
        'deliverables' => ['Content audit', 'Topic strategy', 'SEO briefs', 'Blog and page content'],
        'related' => ['seo', 'social-media', 'lead-generation'],
        'faqs' => [
            ['q' => 'Is content marketing only blogging?', 'a' => 'No. It includes service pages, guides, landing pages, social content and sales assets.'],
            ['q' => 'Do you research keywords first?', 'a' => 'Yes. Search intent and competitor gaps guide the content plan.'],
        ],
    ],
    'video-marketing' => [
        'name' => 'Video and Reel Marketing',
        'title' => 'Video and Reel Marketing for Campaigns and Social Growth',
        'meta' => 'Plan short-form video, reels and campaign content that builds trust and supports lead generation.',
        'intro' => 'Short-form video helps brands explain value quickly, show proof and stay visible in crowded feeds.',
        'proof' => 'We plan hooks, scripts, formats, posting use cases and ad adaptations so video supports the funnel.',
        'icon' => 'video',
        'outcomes' => ['More engaging content', 'Stronger ad creatives', 'Better product education', 'Reusable clips'],
        'deliverables' => ['Video content plan', 'Script hooks', 'Reel concepts', 'Campaign adaptation'],
        'related' => ['meta-ads', 'social-media', 'branding'],
        'faqs' => [
            ['q' => 'Do reels help service businesses?', 'a' => 'Yes. Reels can explain problems, show process, answer FAQs and support retargeting.'],
            ['q' => 'Can video content be used in ads?', 'a' => 'Yes. We plan formats that can work for both organic posts and paid campaigns.'],
        ],
    ],
    'ecommerce-marketing' => [
        'name' => 'Ecommerce Marketing',
        'title' => 'Ecommerce Marketing for Traffic, Conversions and Repeat Sales',
        'meta' => 'Grow ecommerce sales with SEO, ads, analytics, creative testing and lifecycle marketing from Mega Techzy.',
        'intro' => 'Ecommerce growth needs product visibility, conversion optimization, retargeting and retention working together.',
        'proof' => 'We connect acquisition campaigns, product-page improvements, tracking and email or WhatsApp follow-up flows.',
        'icon' => 'cart',
        'outcomes' => ['More qualified traffic', 'Better product discovery', 'Improved conversion rate', 'Repeat purchase support'],
        'deliverables' => ['Store audit', 'Campaign plan', 'Tracking setup', 'Retention workflow'],
        'related' => ['google-ads', 'meta-ads', 'email-marketing'],
        'faqs' => [
            ['q' => 'Can you market Shopify or WooCommerce stores?', 'a' => 'Yes. We can support common ecommerce platforms with ads, SEO and analytics.'],
            ['q' => 'Do you optimize product pages?', 'a' => 'Yes. Product titles, copy, images, internal links and tracking can all affect results.'],
        ],
    ],
    'lead-generation' => [
        'name' => 'Lead Generation',
        'title' => 'Lead Generation Company in Pune for Qualified Business Enquiries',
        'meta' => 'Build lead generation systems with landing pages, ads, SEO, automation and reporting by Mega Techzy.',
        'intro' => 'Lead generation works best as a system: clear offer, strong landing page, targeted traffic, fast follow-up and honest reporting.',
        'proof' => 'We connect website, SEO, ads, tracking and automation so teams can see where leads come from and improve quality over time.',
        'icon' => 'funnel',
        'outcomes' => ['More qualified enquiries', 'Lower wasted spend', 'Faster follow-up', 'Clearer lead source data'],
        'deliverables' => ['Funnel strategy', 'Landing page plan', 'Campaign setup', 'Lead tracking and reporting'],
        'related' => ['google-ads', 'website-development', 'analytics'],
        'faqs' => [
            ['q' => 'What counts as a qualified lead?', 'a' => 'A qualified lead matches your target location, service need, budget range and intent to speak or buy.'],
            ['q' => 'Can you improve lead quality?', 'a' => 'Yes. Better targeting, forms, landing pages and follow-up rules can improve the quality of enquiries.'],
        ],
    ],
];

$locations = [
    'pune' => ['name' => 'Pune', 'headline' => 'Digital Marketing Company in Pune', 'keyword' => 'digital marketing company in Pune'],
    'pcmc' => ['name' => 'PCMC', 'headline' => 'Digital Marketing Company in PCMC', 'keyword' => 'digital marketing company in PCMC'],
    'solapur' => ['name' => 'Solapur', 'headline' => 'Website Development Company in Solapur', 'keyword' => 'website development company in Solapur'],
    'nigdi' => ['name' => 'Nigdi', 'headline' => 'Digital Marketing Services in Nigdi', 'keyword' => 'digital marketing services in Nigdi'],
    'pimpri' => ['name' => 'Pimpri', 'headline' => 'SEO and Website Development in Pimpri', 'keyword' => 'SEO company in Pimpri'],
    'chinchwad' => ['name' => 'Chinchwad', 'headline' => 'Website Development and Ads in Chinchwad', 'keyword' => 'website development company in Chinchwad'],
    'wakad' => ['name' => 'Wakad', 'headline' => 'Lead Generation and SEO in Wakad', 'keyword' => 'lead generation company in Wakad'],
    'baner' => ['name' => 'Baner', 'headline' => 'Branding and Digital Marketing in Baner', 'keyword' => 'branding agency in Baner'],
    'hinjawadi' => ['name' => 'Hinjawadi', 'headline' => 'B2B Digital Marketing in Hinjawadi', 'keyword' => 'B2B digital marketing in Hinjawadi'],
    'moshi' => ['name' => 'Moshi', 'headline' => 'Local SEO and Website Design in Moshi', 'keyword' => 'local SEO services in Moshi'],
    'bhosari' => ['name' => 'Bhosari', 'headline' => 'Industrial Marketing Services in Bhosari', 'keyword' => 'industrial marketing agency in Bhosari'],
    'chakan' => ['name' => 'Chakan', 'headline' => 'Manufacturing Lead Generation in Chakan', 'keyword' => 'manufacturing lead generation in Chakan'],
    'talegaon' => ['name' => 'Talegaon', 'headline' => 'Digital Marketing for Talegaon Businesses', 'keyword' => 'digital marketing services in Talegaon'],
];

$industries = ['Manufacturing', 'Real Estate', 'Healthcare', 'Education', 'Retail', 'Ecommerce', 'Professional Services', 'Local Businesses'];

$portfolioItems = [
    ['title' => 'B2B Manufacturer Growth System', 'type' => 'SEO + Lead Generation', 'result' => 'Built service pages, tracking and search campaigns for higher-quality enquiries.'],
    ['title' => 'Local Clinic Visibility Upgrade', 'type' => 'Website + Local SEO', 'result' => 'Improved trust signals, appointment paths and location relevance.'],
    ['title' => 'Retail Brand Launch', 'type' => 'Branding + Meta Ads', 'result' => 'Created launch creatives, audience testing and retargeting journeys.'],
];

$blogPosts = [
    ['title' => 'How to Choose a Digital Marketing Company in Pune', 'slug' => 'choose-digital-marketing-company-pune', 'excerpt' => 'A practical checklist for comparing strategy, reporting, local SEO knowledge and lead quality.'],
    ['title' => 'Website Features Every Local Business Needs', 'slug' => 'local-business-website-features', 'excerpt' => 'The pages, trust signals and conversion tools that turn a brochure website into a lead engine.'],
    ['title' => 'SEO vs Google Ads: Which Should You Start First?', 'slug' => 'seo-vs-google-ads', 'excerpt' => 'How to decide between immediate demand capture and long-term organic growth.'],
    ['title' => 'Local SEO Checklist for Pune Businesses', 'slug' => 'local-seo-checklist-pune-businesses', 'excerpt' => 'A practical local SEO checklist for Pune businesses that want more calls, direction requests and qualified enquiries.', 'keyword' => 'local SEO checklist for Pune businesses', 'audience' => 'Pune service businesses', 'outcome' => 'improve local visibility and capture more nearby enquiries'],
    ['title' => 'Google Business Profile Optimization for Pune Companies', 'slug' => 'google-business-profile-optimization-pune', 'excerpt' => 'Learn how Pune companies can make their Google Business Profile clearer, more useful and more conversion-ready.', 'keyword' => 'Google Business Profile optimization Pune', 'audience' => 'Pune business owners', 'outcome' => 'turn map visibility into calls and visits'],
    ['title' => 'How Much Does a Business Website Cost in Pune?', 'slug' => 'business-website-cost-pune', 'excerpt' => 'A transparent guide to website cost in Pune, including scope, features, content and ongoing optimisation.', 'keyword' => 'business website cost in Pune', 'audience' => 'business owners planning a new website', 'outcome' => 'set a realistic website budget and avoid expensive gaps'],
    ['title' => 'Best Website Design Practices for Manufacturing Companies', 'slug' => 'website-design-manufacturing-companies', 'excerpt' => 'How manufacturing businesses can build a credible, technical and lead-ready website that supports sales.', 'keyword' => 'website design for manufacturing companies', 'audience' => 'manufacturing and industrial teams', 'outcome' => 'earn trust with buyers and generate specification-led enquiries'],
    ['title' => 'Real Estate Lead Generation Ideas for Pune Builders', 'slug' => 'real-estate-lead-generation-pune-builders', 'excerpt' => 'Lead generation ideas for Pune builders, from campaign offers and landing pages to follow-up and attribution.', 'keyword' => 'real estate lead generation Pune', 'audience' => 'real estate developers and channel partners', 'outcome' => 'create a dependable project enquiry pipeline'],
    ['title' => 'SEO for Doctors and Clinics in Pune: A Practical Guide', 'slug' => 'seo-doctors-clinics-pune', 'excerpt' => 'A patient-first local SEO guide for doctors and clinics in Pune, including trust content and appointment paths.', 'keyword' => 'SEO for doctors and clinics in Pune', 'audience' => 'clinics and healthcare practices', 'outcome' => 'help suitable patients find and trust the practice'],
    ['title' => 'Digital Marketing for Schools and Coaching Classes', 'slug' => 'digital-marketing-schools-coaching-classes', 'excerpt' => 'A guide to ethical, parent-friendly digital marketing for schools, tuition centres and coaching classes.', 'keyword' => 'digital marketing for coaching classes', 'audience' => 'education providers', 'outcome' => 'increase relevant admissions and enquiry quality'],
    ['title' => 'Google Ads for Local Services: A Beginner Guide', 'slug' => 'google-ads-local-services-guide', 'excerpt' => 'How local service businesses can use Google Ads to capture high-intent searches without wasting budget.', 'keyword' => 'Google Ads for local services', 'audience' => 'local service providers', 'outcome' => 'capture urgent and high-intent demand responsibly'],
    ['title' => 'Landing Page Checklist for Better Lead Generation', 'slug' => 'landing-page-checklist-lead-generation', 'excerpt' => 'A conversion-focused landing page checklist covering offer clarity, proof, forms, speed and tracking.', 'keyword' => 'landing page checklist for lead generation', 'audience' => 'businesses running paid campaigns', 'outcome' => 'convert more of the traffic already being paid for'],
    ['title' => 'WhatsApp Lead Follow-Up Strategy for Small Businesses', 'slug' => 'whatsapp-lead-follow-up-small-business', 'excerpt' => 'Build a helpful WhatsApp lead follow-up flow that improves response time without becoming spammy.', 'keyword' => 'WhatsApp lead follow up strategy for small business', 'audience' => 'small business sales teams', 'outcome' => 'respond faster and move genuine leads toward a conversation'],
    ['title' => 'GA4 Setup Guide for Lead Generation Websites', 'slug' => 'ga4-setup-lead-generation-websites', 'excerpt' => 'The core GA4 events, conversions and reporting checks every lead generation website should have.', 'keyword' => 'GA4 setup for lead generation website', 'audience' => 'marketing teams and business owners', 'outcome' => 'make campaign decisions with more reliable lead data'],
    ['title' => 'Technical SEO Checklist for New Business Websites', 'slug' => 'technical-seo-checklist-new-website', 'excerpt' => 'A plain-English technical SEO checklist for launching a crawlable, fast and indexable business website.', 'keyword' => 'technical SEO checklist for new website', 'audience' => 'new website owners', 'outcome' => 'launch with fewer technical blockers and clearer search signals'],
    ['title' => 'Content Marketing Ideas for B2B Companies in India', 'slug' => 'content-marketing-ideas-b2b-india', 'excerpt' => 'Useful B2B content marketing ideas for Indian companies that need to educate buyers and create demand.', 'keyword' => 'content marketing ideas for B2B companies in India', 'audience' => 'B2B marketing and sales teams', 'outcome' => 'answer buyer questions before the sales call'],
    ['title' => 'Instagram Reels Ideas for Local Businesses', 'slug' => 'instagram-reels-ideas-local-businesses', 'excerpt' => 'Practical Instagram Reels ideas that help local businesses show proof, explain services and stay memorable.', 'keyword' => 'Instagram Reels ideas for local businesses', 'audience' => 'local business owners and marketing teams', 'outcome' => 'create repeatable social content that supports trust'],
    ['title' => 'Ecommerce Product Page SEO Checklist', 'slug' => 'ecommerce-product-page-seo-checklist', 'excerpt' => 'Improve product discovery and shopper confidence with this ecommerce product page SEO checklist.', 'keyword' => 'ecommerce product page SEO checklist', 'audience' => 'ecommerce store owners', 'outcome' => 'make product pages easier to discover and easier to buy from'],
    ['title' => 'How to Reduce Cost Per Lead in Google Ads', 'slug' => 'reduce-cost-per-lead-google-ads', 'excerpt' => 'A practical framework for reducing wasted Google Ads spend while protecting lead quality.', 'keyword' => 'how to reduce cost per lead in Google Ads', 'audience' => 'businesses already running search ads', 'outcome' => 'improve efficiency without chasing cheap but poor-quality leads'],
    ['title' => 'Website Speed Optimization Tips for Small Businesses', 'slug' => 'website-speed-optimization-small-business', 'excerpt' => 'Simple website speed optimization priorities that improve mobile experience, conversion confidence and SEO readiness.', 'keyword' => 'website speed optimization for small business', 'audience' => 'small business website owners', 'outcome' => 'make the website feel quicker and easier to use'],
    ['title' => 'Local SEO for Solapur Businesses: Where to Start', 'slug' => 'local-seo-solapur-businesses', 'excerpt' => 'A practical starting plan for Solapur businesses that want to improve local discovery and enquiries.', 'keyword' => 'local SEO for Solapur businesses', 'audience' => 'Solapur business owners', 'outcome' => 'build local search visibility step by step'],
    ['title' => 'Digital Marketing Strategy for Startups in Pune', 'slug' => 'digital-marketing-strategy-startups-pune', 'excerpt' => 'A focused digital marketing strategy for Pune startups choosing where to invest their first marketing budget.', 'keyword' => 'digital marketing strategy for startups in Pune', 'audience' => 'Pune startup founders', 'outcome' => 'prioritise a lean marketing system around real demand'],
    ['title' => 'B2B Lead Generation Strategy for Industrial Companies', 'slug' => 'b2b-lead-generation-industrial-companies', 'excerpt' => 'How industrial companies can combine technical content, search intent and follow-up for stronger B2B leads.', 'keyword' => 'B2B lead generation for industrial companies', 'audience' => 'industrial B2B companies', 'outcome' => 'create more sales-ready conversations with target accounts'],
    ['title' => 'Best AI Tools for Small Businesses in India', 'slug' => 'best-ai-tools-small-businesses-india', 'excerpt' => 'A practical guide to choosing AI tools for small businesses in India without losing control of customer data or quality.', 'keyword' => 'best AI tools for small businesses in India', 'audience' => 'Indian small business owners', 'outcome' => 'use AI where it saves time while keeping human judgement in the process'],
    ['title' => 'AI Tools for Digital Marketing Agencies', 'slug' => 'ai-tools-digital-marketing-agencies', 'excerpt' => 'How digital marketing agencies can evaluate AI tools for planning, research, reporting and creative workflows.', 'keyword' => 'AI tools for digital marketing agencies', 'audience' => 'digital marketing agencies', 'outcome' => 'build quicker, more reliable marketing workflows'],
    ['title' => 'AI Tools for Content Writing: A Responsible Workflow', 'slug' => 'ai-tools-content-writing-workflow', 'excerpt' => 'Use AI tools for content writing responsibly, with original expertise, fact checking and a clear editorial process.', 'keyword' => 'AI tools for content writing', 'audience' => 'content teams and business owners', 'outcome' => 'create useful, accurate content without publishing generic output'],
    ['title' => 'AI Tools for Social Media Managers', 'slug' => 'ai-tools-social-media-managers', 'excerpt' => 'A practical AI tools guide for social media managers planning content, repurposing ideas and reviewing performance.', 'keyword' => 'AI tools for social media managers', 'audience' => 'social media managers', 'outcome' => 'make content operations more consistent without losing the brand voice'],
    ['title' => 'AI Tools for SEO Research and Content Planning', 'slug' => 'ai-tools-seo-research-content-planning', 'excerpt' => 'How to use AI tools for SEO research and content planning while keeping originality, accuracy and search intent first.', 'keyword' => 'AI tools for SEO research', 'audience' => 'SEO teams and business marketers', 'outcome' => 'turn real search questions into a stronger content plan'],
    ['title' => 'AI Tools for Customer Support in Small Businesses', 'slug' => 'ai-tools-customer-support-small-business', 'excerpt' => 'A guide to selecting AI tools for customer support, including handoff rules, knowledge quality and customer trust.', 'keyword' => 'AI tools for customer support small business', 'audience' => 'small business support teams', 'outcome' => 'reply faster while preserving useful human support when it matters'],
    ['title' => 'AI Tools for Sales Lead Generation', 'slug' => 'ai-tools-sales-lead-generation', 'excerpt' => 'How sales teams can use AI tools for lead research, qualification and follow-up without automating poor outreach.', 'keyword' => 'AI tools for sales lead generation', 'audience' => 'sales teams and lead generation managers', 'outcome' => 'focus sales effort on more relevant conversations'],
    ['title' => 'AI Tools for Website Design and Content Planning', 'slug' => 'ai-tools-website-design-content-planning', 'excerpt' => 'Use AI tools to support website planning, content structure and conversion review while keeping the website human-centred.', 'keyword' => 'AI tools for website design', 'audience' => 'businesses planning a new website', 'outcome' => 'make better website decisions before design and development begin'],
    ['title' => 'AI Tools for Real Estate Marketing', 'slug' => 'ai-tools-real-estate-marketing', 'excerpt' => 'A responsible AI tools guide for real estate marketing, from campaign planning to enquiry response and reporting.', 'keyword' => 'AI tools for real estate marketing', 'audience' => 'real estate marketing teams', 'outcome' => 'improve marketing operations while protecting buyer trust'],
    ['title' => 'AI Tools for Ecommerce Product Descriptions', 'slug' => 'ai-tools-ecommerce-product-descriptions', 'excerpt' => 'How ecommerce teams can use AI tools for product descriptions without publishing inaccurate, repetitive or weak copy.', 'keyword' => 'AI tools for ecommerce product descriptions', 'audience' => 'ecommerce store owners and product teams', 'outcome' => 'produce clearer product content with a strong quality review process'],
    ['title' => 'What Is WordPress and Why Do Businesses Use It?', 'slug' => 'what-is-wordpress-business-guide', 'excerpt' => 'A simple WordPress guide for businesses comparing flexible website platforms, content control and long-term growth.', 'keyword' => 'what is WordPress for business', 'audience' => 'business owners planning a website', 'outcome' => 'understand whether WordPress fits their website needs', 'help' => 'Mega Techzy plans, designs and develops WordPress websites with a clear content structure, fast mobile experience, secure forms and SEO-ready foundations.', 'help_url' => '/services/website-development.php'],
    ['title' => 'WordPress Website vs Custom Website: Which Is Better?', 'slug' => 'wordpress-vs-custom-website', 'excerpt' => 'Compare WordPress and custom website development by control, cost, security, performance and business needs.', 'keyword' => 'WordPress website vs custom website', 'audience' => 'business owners choosing a website platform', 'outcome' => 'choose the right development approach for their requirements', 'help' => 'Mega Techzy helps businesses choose and build the right website approach, with strategy, UX, technical SEO and conversion paths planned before development starts.', 'help_url' => '/services/website-development.php'],
    ['title' => 'Top 10 Benefits of a WordPress Website for Small Businesses', 'slug' => 'top-benefits-wordpress-website-small-business', 'excerpt' => 'Discover the practical benefits of a WordPress website for small businesses that need flexibility, speed and easier content updates.', 'keyword' => 'benefits of WordPress website for small business', 'audience' => 'small business owners', 'outcome' => 'use a website platform that supports ongoing marketing', 'help' => 'Mega Techzy builds WordPress websites that are easy to expand with service pages, blogs, local SEO content and lead-generation features.', 'help_url' => '/services/website-development.php'],
    ['title' => 'Top 5 WordPress Security Practices for Business Websites', 'slug' => 'top-wordpress-security-practices-business-websites', 'excerpt' => 'A business-friendly WordPress security checklist covering updates, access control, backups and safe website operations.', 'keyword' => 'WordPress security practices for business websites', 'audience' => 'business website owners', 'outcome' => 'reduce avoidable website security risks', 'help' => 'Mega Techzy can review website foundations, secure enquiry paths and help businesses plan a safer, maintainable website build.', 'help_url' => '/services/website-development.php'],
    ['title' => 'Top 10 WordPress SEO Tips for Business Websites', 'slug' => 'top-wordpress-seo-tips-business-websites', 'excerpt' => 'Practical WordPress SEO tips for businesses that want a better content structure, local visibility and technical foundation.', 'keyword' => 'WordPress SEO tips for business websites', 'audience' => 'WordPress website owners', 'outcome' => 'make their site easier for customers and search engines to understand', 'help' => 'Mega Techzy combines technical SEO, page structure, content planning and local search improvements for WordPress business websites.', 'help_url' => '/services/seo.php'],
    ['title' => 'What Is cPanel Hosting and How Does It Work?', 'slug' => 'what-is-cpanel-hosting', 'excerpt' => 'A beginner-friendly explanation of cPanel hosting, what it manages and how business owners should use it safely.', 'keyword' => 'what is cPanel hosting', 'audience' => 'new website owners', 'outcome' => 'understand the basics of managing website hosting', 'help' => 'Mega Techzy helps with website launch planning, hosting setup coordination, domain connection and technical checks before a website goes live.', 'help_url' => '/services/website-development.php'],
    ['title' => 'Top 10 cPanel Features Every Website Owner Should Know', 'slug' => 'top-cpanel-features-website-owner', 'excerpt' => 'Learn the cPanel features that matter most for files, backups, email, domains and basic website maintenance.', 'keyword' => 'cPanel features for website owners', 'audience' => 'business owners managing hosting', 'outcome' => 'handle essential hosting tasks with more confidence', 'help' => 'Mega Techzy can help set up the website and document the key access, backup and launch checks your business needs.', 'help_url' => '/services/website-development.php'],
    ['title' => 'What Is Web Hosting? A Simple Guide for Beginners', 'slug' => 'what-is-web-hosting-beginners-guide', 'excerpt' => 'Understand web hosting in simple terms, including what it does, why it matters and how it affects a business website.', 'keyword' => 'what is web hosting', 'audience' => 'business owners new to websites', 'outcome' => 'make more informed website hosting decisions', 'help' => 'Mega Techzy guides businesses through website planning and launch so the hosting, domain, website and enquiry setup work together.', 'help_url' => '/services/website-development.php'],
    ['title' => 'Shared Hosting vs VPS vs Cloud Hosting: Which Is Better?', 'slug' => 'shared-vps-cloud-hosting-comparison', 'excerpt' => 'Compare shared, VPS and cloud hosting based on website needs, performance expectations, control and support.', 'keyword' => 'shared hosting vs VPS vs cloud hosting', 'audience' => 'businesses comparing website hosting options', 'outcome' => 'choose a hosting path that matches their website stage', 'help' => 'Mega Techzy can assess the website scope and recommend a launch setup that supports performance, security and future marketing needs.', 'help_url' => '/services/website-development.php'],
    ['title' => 'Top 5 Tips to Choose Web Hosting for a Business Website', 'slug' => 'top-tips-choose-web-hosting-business-website', 'excerpt' => 'Use this practical hosting checklist to compare reliability, support, backups, security and room to grow.', 'keyword' => 'how to choose web hosting for business website', 'audience' => 'businesses buying hosting', 'outcome' => 'avoid common hosting selection mistakes', 'help' => 'Mega Techzy supports website projects from planning to launch, including technical checks that keep the site ready for SEO and lead generation.', 'help_url' => '/services/website-development.php'],
    ['title' => 'What Is a Domain Name and Why Does Your Business Need One?', 'slug' => 'what-is-domain-name-business', 'excerpt' => 'A simple guide to domain names, brand identity, website access and why the right domain matters for businesses.', 'keyword' => 'what is a domain name for business', 'audience' => 'new business owners', 'outcome' => 'choose and manage a domain with more confidence', 'help' => 'Mega Techzy helps businesses connect their domain, hosting and website correctly so customers reach a professional, secure online presence.', 'help_url' => '/services/website-development.php'],
    ['title' => 'Domain Name vs Web Hosting: What Is the Difference?', 'slug' => 'domain-name-vs-web-hosting', 'excerpt' => 'Understand the difference between a domain name and web hosting before you buy or launch a business website.', 'keyword' => 'domain name vs web hosting', 'audience' => 'business owners starting a website', 'outcome' => 'make the right website setup decisions', 'help' => 'Mega Techzy can handle the practical website setup journey, including domain connection, hosting coordination, website development and launch testing.', 'help_url' => '/services/website-development.php'],
    ['title' => 'Top 10 Tips to Choose a Good Domain Name for Your Business', 'slug' => 'top-tips-choose-domain-name-business', 'excerpt' => 'Choose a memorable, credible and future-friendly domain name with this practical business checklist.', 'keyword' => 'how to choose a domain name for business', 'audience' => 'business founders and owners', 'outcome' => 'select a domain that supports recognition and trust', 'help' => 'Mega Techzy helps turn a business idea into a coherent digital presence, from domain choice to website structure and conversion-focused content.', 'help_url' => '/services/website-development.php'],
    ['title' => 'Top 5 Domain Extensions for Indian Businesses', 'slug' => 'top-domain-extensions-indian-businesses', 'excerpt' => 'Compare common domain extensions for Indian businesses by audience, brand fit, availability and long-term use.', 'keyword' => 'best domain extensions for Indian businesses', 'audience' => 'Indian businesses choosing a domain', 'outcome' => 'select a domain extension that suits their audience', 'help' => 'Mega Techzy can guide the early website choices that affect brand clarity, technical setup and a smooth customer journey.', 'help_url' => '/services/website-development.php'],
    ['title' => 'What Is Digital Marketing? A Beginner Guide for Businesses', 'slug' => 'what-is-digital-marketing-beginner-guide', 'excerpt' => 'Understand digital marketing in plain language, including websites, search, ads, content, social media and lead follow-up.', 'keyword' => 'what is digital marketing for business', 'audience' => 'business owners new to digital marketing', 'outcome' => 'understand the channels that can support their growth', 'help' => 'Mega Techzy connects website development, SEO, paid ads, social media, automation and analytics into a practical marketing plan.', 'help_url' => '/services/lead-generation.php'],
    ['title' => 'Why Is Digital Marketing Important for Small Businesses?', 'slug' => 'why-digital-marketing-important-small-business', 'excerpt' => 'Learn why digital marketing matters for small businesses seeking visibility, trust, local enquiries and measurable growth.', 'keyword' => 'why digital marketing is important for small business', 'audience' => 'small business owners', 'outcome' => 'prioritise digital work around real business goals', 'help' => 'Mega Techzy helps small businesses choose the right mix of local SEO, website improvements, ads and follow-up based on their market and budget.', 'help_url' => '/services/lead-generation.php'],
    ['title' => 'Top 10 Benefits of Digital Marketing for Local Businesses', 'slug' => 'top-benefits-digital-marketing-local-businesses', 'excerpt' => 'Explore the benefits of digital marketing for local businesses that want better discovery, trust and qualified enquiries.', 'keyword' => 'benefits of digital marketing for local businesses', 'audience' => 'local business owners', 'outcome' => 'build a more visible and measurable local presence', 'help' => 'Mega Techzy supports local growth through SEO, Google Ads, conversion-focused websites and reporting that connects activity to enquiries.', 'help_url' => '/services/seo.php'],
    ['title' => 'Traditional Marketing vs Digital Marketing: Which Is Better?', 'slug' => 'traditional-marketing-vs-digital-marketing', 'excerpt' => 'Compare traditional and digital marketing by reach, targeting, measurement, speed and local business goals.', 'keyword' => 'traditional marketing vs digital marketing', 'audience' => 'business owners planning a marketing budget', 'outcome' => 'make a clearer channel investment decision', 'help' => 'Mega Techzy helps businesses make digital marketing decisions based on target customers, service areas, sales process and measurable next steps.', 'help_url' => '/services/lead-generation.php'],
    ['title' => 'Top 5 Digital Marketing Strategies for Service Businesses', 'slug' => 'top-digital-marketing-strategies-service-businesses', 'excerpt' => 'Five practical digital marketing strategies for service businesses that need qualified leads, not vanity metrics.', 'keyword' => 'digital marketing strategies for service businesses', 'audience' => 'service business owners', 'outcome' => 'create a focused plan for generating relevant enquiries', 'help' => 'Mega Techzy builds lead-generation systems around clear offers, landing pages, SEO, ads, measurement and faster follow-up.', 'help_url' => '/services/lead-generation.php'],
    ['title' => 'Google Ads vs Social Media Ads: Which Should You Choose?', 'slug' => 'google-ads-vs-social-media-ads', 'excerpt' => 'A practical comparison of Google Ads and social media ads by intent, timing, creative, targeting and lead quality.', 'keyword' => 'Google Ads vs social media ads', 'audience' => 'businesses considering paid advertising', 'outcome' => 'choose the right paid channel for their immediate goal', 'help' => 'Mega Techzy plans and manages Google Ads and Meta Ads with a focus on audience fit, landing pages, tracking and lead quality.', 'help_url' => '/services/google-ads.php'],
    ['title' => 'What Is Marketing Automation and How Does It Work?', 'slug' => 'what-is-marketing-automation-how-it-works', 'excerpt' => 'A beginner-friendly guide to marketing automation, lead journeys, triggers, follow-up and responsible implementation.', 'keyword' => 'what is marketing automation', 'audience' => 'business owners and marketing teams', 'outcome' => 'understand where automation can improve customer follow-up', 'help' => 'Mega Techzy maps practical marketing automation workflows for lead capture, CRM updates, reminders, email sequences and reporting.', 'help_url' => '/services/email-marketing.php'],
    ['title' => 'Top 5 Benefits of Marketing Automation for Businesses', 'slug' => 'top-benefits-marketing-automation-businesses', 'excerpt' => 'Explore how marketing automation can improve response time, lead handling, consistency and reporting for businesses.', 'keyword' => 'benefits of marketing automation for businesses', 'audience' => 'growing business teams', 'outcome' => 'identify high-value automation opportunities', 'help' => 'Mega Techzy designs automation around the customer journey, then connects forms, CRM fields, follow-up messages and useful performance reporting.', 'help_url' => '/services/email-marketing.php'],
    ['title' => 'What Is WhatsApp Automation?', 'slug' => 'what-is-whatsapp-automation', 'excerpt' => 'Understand WhatsApp automation, how it supports faster lead response and where human conversations still matter.', 'keyword' => 'what is WhatsApp automation', 'audience' => 'business owners handling enquiries on WhatsApp', 'outcome' => 'use WhatsApp more consistently without sounding robotic', 'help' => 'Mega Techzy plans WhatsApp workflows with consent-aware messaging, quick handoff to people and lead-source tracking.', 'help_url' => '/services/whatsapp-marketing.php'],
    ['title' => 'Top 10 Benefits of WhatsApp Automation for Lead Follow-Up', 'slug' => 'top-benefits-whatsapp-automation-lead-follow-up', 'excerpt' => 'Learn the benefits of WhatsApp automation for faster follow-up, reminders, lead routing and customer convenience.', 'keyword' => 'benefits of WhatsApp automation for lead follow up', 'audience' => 'sales teams and local businesses', 'outcome' => 'improve response time while protecting lead quality', 'help' => 'Mega Techzy can build WhatsApp follow-up journeys that connect enquiry forms, lead segmentation, template messages and human sales handoff.', 'help_url' => '/services/whatsapp-marketing.php'],
    ['title' => 'WhatsApp Automation vs Manual Follow-Up: Which Is Better?', 'slug' => 'whatsapp-automation-vs-manual-follow-up', 'excerpt' => 'Compare automated and manual WhatsApp follow-up by speed, personalisation, control, customer experience and team workload.', 'keyword' => 'WhatsApp automation vs manual follow up', 'audience' => 'businesses managing incoming leads', 'outcome' => 'choose a balanced follow-up process', 'help' => 'Mega Techzy helps teams combine automation for quick acknowledgement with clear rules for personal sales follow-up when a lead needs attention.', 'help_url' => '/services/whatsapp-marketing.php'],
    ['title' => 'How to Use WhatsApp Automation for Customer Support and Sales', 'slug' => 'whatsapp-automation-customer-support-sales', 'excerpt' => 'A practical WhatsApp automation guide for businesses that need better support, enquiry routing and sales follow-up.', 'keyword' => 'WhatsApp automation for customer support and sales', 'audience' => 'support and sales teams', 'outcome' => 'create a faster, more organised customer communication flow', 'help' => 'Mega Techzy can map support and sales journeys, set up useful message templates and connect WhatsApp actions with lead management workflows.', 'help_url' => '/services/whatsapp-marketing.php'],
    ['title' => 'Top 5 Lead Follow-Up Automation Workflows for Small Businesses', 'slug' => 'top-lead-follow-up-automation-workflows', 'excerpt' => 'Five lead follow-up automation workflows that help small businesses respond faster and keep enquiries organised.', 'keyword' => 'lead follow up automation workflows for small business', 'audience' => 'small business sales teams', 'outcome' => 'reduce missed opportunities after an enquiry arrives', 'help' => 'Mega Techzy builds follow-up systems that connect forms, email, WhatsApp, CRM reminders and reporting around your actual sales process.', 'help_url' => '/services/email-marketing.php'],
    ['title' => 'Top 10 CRM Automation Benefits for Sales Teams', 'slug' => 'top-crm-automation-benefits-sales-teams', 'excerpt' => 'Discover how CRM automation can improve lead assignment, reminders, data quality, reporting and sales team focus.', 'keyword' => 'CRM automation benefits for sales teams', 'audience' => 'sales managers and business owners', 'outcome' => 'make lead management more consistent and measurable', 'help' => 'Mega Techzy can plan CRM and Zoho workflows that keep lead data cleaner, trigger the right next step and make follow-up easier to manage.', 'help_url' => '/services/email-marketing.php'],
    ['title' => 'Email Automation vs WhatsApp Automation: Which Is Better?', 'slug' => 'email-automation-vs-whatsapp-automation', 'excerpt' => 'Compare email and WhatsApp automation by message type, timing, consent, engagement and business use case.', 'keyword' => 'email automation vs WhatsApp automation', 'audience' => 'businesses planning customer communication', 'outcome' => 'use the right channel for each part of the customer journey', 'help' => 'Mega Techzy designs connected email and WhatsApp automation so customers receive useful, timely messages through the channel that fits the moment.', 'help_url' => '/services/email-marketing.php'],
    ['title' => 'Top 5 Automation Mistakes Businesses Should Avoid', 'slug' => 'top-automation-mistakes-businesses-avoid', 'excerpt' => 'Avoid common automation mistakes involving unclear journeys, poor data, spammy messages and missing human support.', 'keyword' => 'automation mistakes businesses should avoid', 'audience' => 'businesses starting automation', 'outcome' => 'launch helpful automation without damaging trust', 'help' => 'Mega Techzy starts automation with journey mapping, consent-aware messaging, testing and human escalation rules instead of a generic blast setup.', 'help_url' => '/services/email-marketing.php'],
];

$homeFaqs = [
    ['q' => 'What does Mega Techzy do?', 'a' => 'Mega Techzy helps businesses grow online through websites, SEO, paid ads, automation, branding, analytics and lead generation.'],
    ['q' => 'Which locations do you serve?', 'a' => 'The primary focus is Pune, PCMC and Solapur, with expansion across Maharashtra and India.'],
    ['q' => 'Can Mega Techzy build both website and marketing campaigns?', 'a' => 'Yes. The team can connect website development, SEO, ads, tracking and follow-up into one growth system.'],
];
