<?php
declare(strict_types=1);

$services = [
    'website-development' => [
        'name' => 'Website Development',
        'title' => 'Website Development Company in Pune for Fast, SEO-Ready Websites',
        'meta' => 'Mega Techzy builds premium business websites in Pune, PCMC and Solapur with SEO, speed, security and lead generation built in from day one.',
        'intro' => 'We design and develop conversion-focused websites that feel premium, load fast and make it easy for customers to trust your business.',
        'proof' => 'Every build includes responsive layouts, technical SEO, analytics setup, secure forms and a content structure that can scale into location and service pages.',
        'icon' => 'code',
        'outcomes' => ['Premium brand presence', 'Better Google crawlability', 'More qualified enquiries', 'Faster mobile experience'],
        'deliverables' => ['UX sitemap and wireframe', 'Responsive PHP/HTML/CSS build', 'On-page SEO foundations', 'Lead form and analytics integration'],
        'related' => ['seo', 'lead-generation', 'analytics'],
        'faqs' => [
            ['q' => 'How long does a business website take?', 'a' => 'Most focused business websites take 2 to 5 weeks depending on page count, content readiness and integrations.'],
            ['q' => 'Do you build SEO into the website?', 'a' => 'Yes. Site structure, metadata, schema, speed, internal links and conversion paths are planned before development begins.'],
        ],
    ],
    'seo' => [
        'name' => 'Search Engine Optimization',
        'title' => 'SEO Company in Pune for Local Rankings and Organic Leads',
        'meta' => 'Improve local rankings, organic traffic and lead quality with Mega Techzy SEO services for Pune, PCMC, Solapur and Maharashtra businesses.',
        'intro' => 'Our SEO programs help search engines understand your business, location relevance, services and proof of expertise.',
        'proof' => 'We combine technical fixes, content planning, local landing pages, Google Business Profile improvements and reporting that connects rankings to leads.',
        'icon' => 'search',
        'outcomes' => ['Higher local visibility', 'More non-paid enquiries', 'Clear content roadmap', 'Improved technical health'],
        'deliverables' => ['SEO audit', 'Keyword and competitor research', 'On-page optimization', 'Local SEO and reporting'],
        'related' => ['content-marketing', 'website-development', 'analytics'],
        'faqs' => [
            ['q' => 'Can SEO help a local Pune business?', 'a' => 'Yes. Local SEO can improve visibility for searches such as digital marketing company in Pune and service-specific local terms.'],
            ['q' => 'When can SEO results start?', 'a' => 'Meaningful movement usually begins within 8 to 12 weeks, with compounding gains as content and authority improve.'],
        ],
    ],
    'google-ads' => [
        'name' => 'Google Ads',
        'title' => 'Google Ads Agency in Pune for Lead Generation Campaigns',
        'meta' => 'Launch conversion-focused Google Ads campaigns with landing pages, tracking and optimization from Mega Techzy.',
        'intro' => 'We run search and performance campaigns that focus on qualified enquiries, not empty clicks.',
        'proof' => 'Campaigns are structured around buyer intent, negative keywords, landing page quality, conversion tracking and weekly optimization.',
        'icon' => 'megaphone',
        'outcomes' => ['Faster demand capture', 'Cleaner search intent', 'Measurable CPL', 'Better landing page quality'],
        'deliverables' => ['Account audit', 'Campaign setup', 'Conversion tracking', 'Search term and bid optimization'],
        'related' => ['lead-generation', 'analytics', 'website-development'],
        'faqs' => [
            ['q' => 'Do you manage small Google Ads budgets?', 'a' => 'Yes. We structure campaigns around the budget, service area and lead target instead of forcing a generic setup.'],
            ['q' => 'Will I know which leads came from ads?', 'a' => 'Yes. We configure conversion tracking through GA4, GTM or platform-native tools wherever possible.'],
        ],
    ],
    'meta-ads' => [
        'name' => 'Meta Ads',
        'title' => 'Meta Ads Agency for Facebook and Instagram Campaigns',
        'meta' => 'Generate awareness, retarget visitors and capture leads with Facebook and Instagram ads managed by Mega Techzy.',
        'intro' => 'Meta campaigns work best when creative, audience, offer and follow-up are aligned. We build that system for growing brands.',
        'proof' => 'We test hooks, creatives, retargeting windows and lead forms while keeping tracking and campaign hygiene tight.',
        'icon' => 'megaphone',
        'outcomes' => ['Stronger brand reach', 'Retargeted website visitors', 'Lead form campaigns', 'Creative testing rhythm'],
        'deliverables' => ['Campaign strategy', 'Creative direction', 'Audience setup', 'Weekly performance optimization'],
        'related' => ['social-media', 'video-marketing', 'lead-generation'],
        'faqs' => [
            ['q' => 'Are Meta Ads good for B2B?', 'a' => 'They can be effective for retargeting, awareness and offer-led lead generation when the funnel is planned properly.'],
            ['q' => 'Do you create ad creatives?', 'a' => 'Yes. We can plan graphics, reels and copy for campaign testing.'],
        ],
    ],
    'linkedin-ads' => [
        'name' => 'LinkedIn Ads',
        'title' => 'LinkedIn Ads for B2B Lead Generation in India',
        'meta' => 'Reach decision makers with LinkedIn Ads strategy, targeting, creative and reporting by Mega Techzy.',
        'intro' => 'LinkedIn Ads help B2B companies reach specific roles, industries and company sizes with a focused message.',
        'proof' => 'We design campaigns for high-value audiences, clean conversion paths and sales follow-up readiness.',
        'icon' => 'linkedin',
        'outcomes' => ['Decision-maker reach', 'B2B lead quality', 'Account-based targeting', 'Stronger remarketing'],
        'deliverables' => ['Audience strategy', 'Campaign setup', 'Creative testing', 'Lead quality review'],
        'related' => ['lead-generation', 'content-marketing', 'analytics'],
        'faqs' => [
            ['q' => 'Is LinkedIn Ads expensive?', 'a' => 'Clicks can cost more than other platforms, so we use LinkedIn when targeting precision and lead value justify it.'],
            ['q' => 'Can LinkedIn Ads support sales teams?', 'a' => 'Yes. Campaigns can be built around lead magnets, demo requests and account-based follow-up.'],
        ],
    ],
    'email-marketing' => [
        'name' => 'Email Marketing and Zoho Automation',
        'title' => 'Email Marketing and Zoho Automation for Better Follow-Up',
        'meta' => 'Automate lead nurturing, follow-ups and reporting with email marketing and Zoho workflows from Mega Techzy.',
        'intro' => 'Most leads need consistent follow-up. We build email and Zoho automations that keep prospects moving.',
        'proof' => 'Workflows can include segmentation, CRM fields, lead source tracking, sales reminders and lifecycle reporting.',
        'icon' => 'automation',
        'outcomes' => ['Faster response time', 'Better lead nurturing', 'Cleaner CRM data', 'Repeatable follow-up'],
        'deliverables' => ['Journey mapping', 'Email copy', 'Zoho workflow setup', 'Testing and reporting'],
        'related' => ['lead-generation', 'whatsapp-marketing', 'analytics'],
        'faqs' => [
            ['q' => 'Can you work with Zoho CRM?', 'a' => 'Yes. We can plan and configure practical Zoho automations for lead capture and follow-up.'],
            ['q' => 'Do you write the email content?', 'a' => 'Yes. We write concise, conversion-focused email sequences based on the customer journey.'],
        ],
    ],
    'whatsapp-marketing' => [
        'name' => 'WhatsApp Marketing',
        'title' => 'WhatsApp Marketing for Lead Follow-Up and Customer Engagement',
        'meta' => 'Use WhatsApp campaigns and follow-up flows to improve response rates and customer engagement with Mega Techzy.',
        'intro' => 'WhatsApp can turn slow follow-up into timely conversations when it is used with consent, context and helpful messaging.',
        'proof' => 'We plan opt-in flows, templates, segmentation and handoff points so WhatsApp supports sales instead of spamming customers.',
        'icon' => 'whatsapp',
        'outcomes' => ['Higher response rates', 'Quicker lead contact', 'Segmented campaigns', 'Better sales handoff'],
        'deliverables' => ['Messaging strategy', 'Template planning', 'Audience segmentation', 'Campaign reporting'],
        'related' => ['email-marketing', 'lead-generation', 'meta-ads'],
        'faqs' => [
            ['q' => 'Is WhatsApp marketing suitable for every business?', 'a' => 'It works best when customers expect quick updates, consultations, bookings or support.'],
            ['q' => 'Do you help avoid spammy messaging?', 'a' => 'Yes. We prioritize consent, useful context and sensible frequency.'],
        ],
    ],
    'analytics' => [
        'name' => 'Analytics, GA4 and GTM',
        'title' => 'GA4, GTM and Looker Studio Analytics Setup',
        'meta' => 'Measure leads, campaigns and website performance with GA4, GTM and Looker Studio dashboards by Mega Techzy.',
        'intro' => 'Good marketing decisions need clean measurement. We set up analytics that make lead sources and performance easier to trust.',
        'proof' => 'We configure events, conversions, tags, dashboard views and checks so reporting supports real business decisions.',
        'icon' => 'chart',
        'outcomes' => ['Reliable conversion data', 'Campaign attribution', 'Readable dashboards', 'Cleaner optimization'],
        'deliverables' => ['GA4 setup', 'GTM configuration', 'Conversion events', 'Looker Studio dashboard'],
        'related' => ['google-ads', 'seo', 'lead-generation'],
        'faqs' => [
            ['q' => 'Can you fix broken tracking?', 'a' => 'Yes. We audit tags, events, forms and thank-you flows to find gaps.'],
            ['q' => 'Do dashboards update automatically?', 'a' => 'Looker Studio dashboards can refresh from connected data sources when configured correctly.'],
        ],
    ],
    'branding' => [
        'name' => 'Branding and Graphic Design',
        'title' => 'Branding Agency in Pune for Modern Business Identity',
        'meta' => 'Create a consistent brand identity, marketing creatives and design system with Mega Techzy branding services.',
        'intro' => 'Strong branding makes your business easier to remember, trust and choose across every customer touchpoint.',
        'proof' => 'We connect logo, color, typography, social creatives and website design into one consistent visual system.',
        'icon' => 'palette',
        'outcomes' => ['Professional identity', 'Consistent campaigns', 'Better recall', 'Stronger website trust'],
        'deliverables' => ['Brand direction', 'Logo refinement', 'Social creatives', 'Website visual system'],
        'related' => ['website-development', 'social-media', 'content-marketing'],
        'faqs' => [
            ['q' => 'Can you refresh an existing brand?', 'a' => 'Yes. We can modernize the visual language while preserving recognition.'],
            ['q' => 'Do you design social media creatives?', 'a' => 'Yes. Branding can include templates and campaign graphics for ongoing marketing.'],
        ],
    ],
    'social-media' => [
        'name' => 'Social Media Management',
        'title' => 'Social Media Management for Consistent Brand Growth',
        'meta' => 'Plan, create and manage social media content that supports brand trust, campaigns and lead generation.',
        'intro' => 'Social media works when it has a clear role: trust-building, education, demand creation or campaign support.',
        'proof' => 'We create calendars, content pillars, captions, creatives and reports that align with business goals.',
        'icon' => 'share',
        'outcomes' => ['Consistent posting', 'Better brand trust', 'Campaign support', 'Clear content direction'],
        'deliverables' => ['Content strategy', 'Monthly calendar', 'Creative production', 'Performance reporting'],
        'related' => ['meta-ads', 'branding', 'video-marketing'],
        'faqs' => [
            ['q' => 'Do you post for businesses monthly?', 'a' => 'Yes. We can manage monthly calendars, creatives, captions and publishing workflows.'],
            ['q' => 'Can social media generate leads?', 'a' => 'It can support lead generation when paired with offers, ads, retargeting and clear calls to action.'],
        ],
    ],
    'content-marketing' => [
        'name' => 'Content Marketing',
        'title' => 'Content Marketing for SEO, Trust and Demand Generation',
        'meta' => 'Build useful blogs, landing pages and content assets that improve SEO visibility and buyer trust.',
        'intro' => 'Content should answer buyer questions better than competitors while guiding readers toward the next step.',
        'proof' => 'We plan topic clusters, service pages, local content and sales enablement assets with SEO intent in mind.',
        'icon' => 'search',
        'outcomes' => ['More search coverage', 'Better buyer education', 'Reusable sales assets', 'Stronger authority'],
        'deliverables' => ['Content audit', 'Topic strategy', 'SEO briefs', 'Blog and page content'],
        'related' => ['seo', 'social-media', 'lead-generation'],
        'faqs' => [
            ['q' => 'Is content marketing only blogging?', 'a' => 'No. It includes service pages, guides, landing pages, social content and sales assets.'],
            ['q' => 'Do you research keywords first?', 'a' => 'Yes. Search intent and competitor gaps guide the content plan.'],
        ],
    ],
    'video-marketing' => [
        'name' => 'Video and Reel Marketing',
        'title' => 'Video and Reel Marketing for Campaigns and Social Growth',
        'meta' => 'Plan short-form video, reels and campaign content that builds trust and supports lead generation.',
        'intro' => 'Short-form video helps brands explain value quickly, show proof and stay visible in crowded feeds.',
        'proof' => 'We plan hooks, scripts, formats, posting use cases and ad adaptations so video supports the funnel.',
        'icon' => 'video',
        'outcomes' => ['More engaging content', 'Stronger ad creatives', 'Better product education', 'Reusable clips'],
        'deliverables' => ['Video content plan', 'Script hooks', 'Reel concepts', 'Campaign adaptation'],
        'related' => ['meta-ads', 'social-media', 'branding'],
        'faqs' => [
            ['q' => 'Do reels help service businesses?', 'a' => 'Yes. Reels can explain problems, show process, answer FAQs and support retargeting.'],
            ['q' => 'Can video content be used in ads?', 'a' => 'Yes. We plan formats that can work for both organic posts and paid campaigns.'],
        ],
    ],
    'ecommerce-marketing' => [
        'name' => 'Ecommerce Marketing',
        'title' => 'Ecommerce Marketing for Traffic, Conversions and Repeat Sales',
        'meta' => 'Grow ecommerce sales with SEO, ads, analytics, creative testing and lifecycle marketing from Mega Techzy.',
        'intro' => 'Ecommerce growth needs product visibility, conversion optimization, retargeting and retention working together.',
        'proof' => 'We connect acquisition campaigns, product-page improvements, tracking and email or WhatsApp follow-up flows.',
        'icon' => 'cart',
        'outcomes' => ['More qualified traffic', 'Better product discovery', 'Improved conversion rate', 'Repeat purchase support'],
        'deliverables' => ['Store audit', 'Campaign plan', 'Tracking setup', 'Retention workflow'],
        'related' => ['google-ads', 'meta-ads', 'email-marketing'],
        'faqs' => [
            ['q' => 'Can you market Shopify or WooCommerce stores?', 'a' => 'Yes. We can support common ecommerce platforms with ads, SEO and analytics.'],
            ['q' => 'Do you optimize product pages?', 'a' => 'Yes. Product titles, copy, images, internal links and tracking can all affect results.'],
        ],
    ],
    'lead-generation' => [
        'name' => 'Lead Generation',
        'title' => 'Lead Generation Company in Pune for Qualified Business Enquiries',
        'meta' => 'Build lead generation systems with landing pages, ads, SEO, automation and reporting by Mega Techzy.',
        'intro' => 'Lead generation works best as a system: clear offer, strong landing page, targeted traffic, fast follow-up and honest reporting.',
        'proof' => 'We connect website, SEO, ads, tracking and automation so teams can see where leads come from and improve quality over time.',
        'icon' => 'funnel',
        'outcomes' => ['More qualified enquiries', 'Lower wasted spend', 'Faster follow-up', 'Clearer lead source data'],
        'deliverables' => ['Funnel strategy', 'Landing page plan', 'Campaign setup', 'Lead tracking and reporting'],
        'related' => ['google-ads', 'website-development', 'analytics'],
        'faqs' => [
            ['q' => 'What counts as a qualified lead?', 'a' => 'A qualified lead matches your target location, service need, budget range and intent to speak or buy.'],
            ['q' => 'Can you improve lead quality?', 'a' => 'Yes. Better targeting, forms, landing pages and follow-up rules can improve the quality of enquiries.'],
        ],
    ],
];

$locations = [
    'pune' => ['name' => 'Pune', 'headline' => 'Digital Marketing Company in Pune', 'keyword' => 'digital marketing company in Pune'],
    'pcmc' => ['name' => 'PCMC', 'headline' => 'Digital Marketing Company in PCMC', 'keyword' => 'digital marketing company in PCMC'],
    'solapur' => ['name' => 'Solapur', 'headline' => 'Website Development Company in Solapur', 'keyword' => 'website development company in Solapur'],
    'nigdi' => ['name' => 'Nigdi', 'headline' => 'Digital Marketing Services in Nigdi', 'keyword' => 'digital marketing services in Nigdi'],
    'pimpri' => ['name' => 'Pimpri', 'headline' => 'SEO and Website Development in Pimpri', 'keyword' => 'SEO company in Pimpri'],
    'chinchwad' => ['name' => 'Chinchwad', 'headline' => 'Website Development and Ads in Chinchwad', 'keyword' => 'website development company in Chinchwad'],
    'wakad' => ['name' => 'Wakad', 'headline' => 'Lead Generation and SEO in Wakad', 'keyword' => 'lead generation company in Wakad'],
    'baner' => ['name' => 'Baner', 'headline' => 'Branding and Digital Marketing in Baner', 'keyword' => 'branding agency in Baner'],
    'hinjawadi' => ['name' => 'Hinjawadi', 'headline' => 'B2B Digital Marketing in Hinjawadi', 'keyword' => 'B2B digital marketing in Hinjawadi'],
    'moshi' => ['name' => 'Moshi', 'headline' => 'Local SEO and Website Design in Moshi', 'keyword' => 'local SEO services in Moshi'],
    'bhosari' => ['name' => 'Bhosari', 'headline' => 'Industrial Marketing Services in Bhosari', 'keyword' => 'industrial marketing agency in Bhosari'],
    'chakan' => ['name' => 'Chakan', 'headline' => 'Manufacturing Lead Generation in Chakan', 'keyword' => 'manufacturing lead generation in Chakan'],
    'talegaon' => ['name' => 'Talegaon', 'headline' => 'Digital Marketing for Talegaon Businesses', 'keyword' => 'digital marketing services in Talegaon'],
];

$industries = ['Manufacturing', 'Real Estate', 'Healthcare', 'Education', 'Retail', 'Ecommerce', 'Professional Services', 'Local Businesses'];

$portfolioItems = [
    ['title' => 'B2B Manufacturer Growth System', 'type' => 'SEO + Lead Generation', 'result' => 'Built service pages, tracking and search campaigns for higher-quality enquiries.'],
    ['title' => 'Local Clinic Visibility Upgrade', 'type' => 'Website + Local SEO', 'result' => 'Improved trust signals, appointment paths and location relevance.'],
    ['title' => 'Retail Brand Launch', 'type' => 'Branding + Meta Ads', 'result' => 'Created launch creatives, audience testing and retargeting journeys.'],
];

$blogPosts = [
    ['title' => 'How to Choose a Digital Marketing Company in Pune', 'slug' => 'choose-digital-marketing-company-pune', 'excerpt' => 'A practical checklist for comparing strategy, reporting, local SEO knowledge and lead quality.'],
    ['title' => 'Website Features Every Local Business Needs', 'slug' => 'local-business-website-features', 'excerpt' => 'The pages, trust signals and conversion tools that turn a brochure website into a lead engine.'],
    ['title' => 'SEO vs Google Ads: Which Should You Start First?', 'slug' => 'seo-vs-google-ads', 'excerpt' => 'How to decide between immediate demand capture and long-term organic growth.'],
];

$homeFaqs = [
    ['q' => 'What does Mega Techzy do?', 'a' => 'Mega Techzy helps businesses grow online through websites, SEO, paid ads, automation, branding, analytics and lead generation.'],
    ['q' => 'Which locations do you serve?', 'a' => 'The primary focus is Pune, PCMC and Solapur, with expansion across Maharashtra and India.'],
    ['q' => 'Can Mega Techzy build both website and marketing campaigns?', 'a' => 'Yes. The team can connect website development, SEO, ads, tracking and follow-up into one growth system.'],
];
